{
 "title": "Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info, server)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Health Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(argocd_app_info{namespace=~\"$namespace\",dest_server=~\"$cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  {
   "title": "Number Of Healthy Volumes",
   "type": "stat",
   "description": "Healthy volumes are volumes that are attaching to a node and have the number of healthy replicas equals to the expected number of replicas.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==1) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Attached Volumes",
   "type": "stat",
   "description": "Attached volumes are volumes that are currently attaching to a node",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(longhorn_disk_usage_bytes/longhorn_disk_capacity_bytes)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number Of Disabled Nodes",
   "type": "stat",
   "description": "Disabled nodes are nodes that are disabled by the user.  When users disable a node, Longhorn will not use the node's storage for replica scheduling. Note that Longhorn can still attach a volume to disabled nodes because the actual data of the volume could be on a different node.",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Failed Nodes",
   "type": "stat",
   "description": "Failed Nodes are nodes that Longhorn cannot attach volumes to and cannot schedule replicas onto. e.g: when the nodes went down.",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(avg(longhorn_node_count_total) OR on() vector(0)) - (count(longhorn_node_status{condition=\"ready\"}==1) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Number Of Degraded Volumes",
   "type": "stat",
   "description": "Degraded volumes are volumes that have the number of healthy replicas smaller than the expected number of replicas. e.g. User creates a volume with 2 replicas but 1 replicas is failed.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==2) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Detached Volumes",
   "type": "stat",
   "description": "Detached volumes are volumes that aren't currently attaching to a node",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_state==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Number Of Nodes",
   "type": "stat",
   "description": "The total number of nodes in the Longhorn storage system",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(longhorn_node_count_total) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Schedulable Nodes",
   "type": "stat",
   "description": "Schedulable nodes are nodes that Longhorn can use their storage for replica scheduling.",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(longhorn_node_status{condition=\"schedulable\"}==1) OR on() vector(0)) - (count(longhorn_node_status{condition=\"allowScheduling\"}==0) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Number Of Fault Volumes",
   "type": "stat",
   "description": "Fault volumes are volumes that doesn't have any healthy replica.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\", resource=\"memory\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{node=~\"$node\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}