---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    template:
      engineVersion: v2
      data:
        AUTHENTIK_POSTGRESQL__HOST: &dbhost pg-authentik-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__USER: &dbuser {{"'{{ .AUTHENTIK_POSTGRES_USER }}'"}}
        AUTHENTIK_POSTGRESQL__NAME: &dbname "authentik"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbpass {{"'{{ .AUTHENTIK_POSTGRES_PASS }}'"}}

        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: {{"'{{ .AUTHENTIK_POSTGRES_SUPER }}'"}}

        AUTHENTIK_BOOTSTRAP_EMAIL: {{"'{{ .AUTHENTIK_EMAIL }}'"}}
        AUTHENTIK_BOOTSTRAP_PASSWORD: {{"'{{ .AUTHENTIK_PASSWORD }}'"}}
        AUTHENTIK_BOOTSTRAP_TOKEN: {{"'{{ .AUTHENTIK_TOKEN }}'"}}
        AUTHENTIK_SECRET_KEY: {{"'{{ .AUTHENTIK_KEY }}'"}}
  dataFrom:
    - extract:
        key: authentik
