app-template:
  controllers:
    system-upgrade:
      strategy: RollingUpdate
      labels:
        app: &app system-upgrade
      containers:
        system-upgrade:
          image:
            repository: docker.io/rancher/system-upgrade-controller
            tag: v0.15.0@sha256:6eabb80da751aca53f8f0628f36ac15e9d17f241d56b64efc209a4909084f573
          env:
            SYSTEM_UPGRADE_CONTROLLER_DEBUG: false
            SYSTEM_UPGRADE_CONTROLLER_THREADS: 2
            SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: 900
            SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: 99
            SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: IfNotPresent
            SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: registry.k8s.io/kubectl:v1.32.2
            SYSTEM_UPGRADE_JOB_POD_REPLACEMENT_POLICY: Failed
            SYSTEM_UPGRADE_JOB_PRIVILEGED: true
            SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: 900
            SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: 15m
            SYSTEM_UPGRADE_CONTROLLER_NAME: *app
            SYSTEM_UPGRADE_CONTROLLER_NAMESPACE:
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
  defaultPodOptions:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile: { type: RuntimeDefault }
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  serviceAccount:
    name: *app
    create: true
