app-template:
  controllers:
    excalidraw:
      replicas: 2
      strategy: RollingUpdate
      labels:
        app: &app excalidraw
      containers:
        excalidraw:
          image:
            repository: docker.io/excalidraw/excalidraw
            tag: latest@sha256:19109d03fa0a8fa6a5cc0a965b9e55456609594d78116600e043a40132ebf17b
            pullPolicy: IfNotPresent
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
          resources:
            requests:
              cpu: 5m
              memory: 10Mi
            limits:
              memory: 50Mi
      pod:
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: *app
  service:
    excalidraw:
      controller: *app
      labels:
        app: *app
      ipFamilyPolicy: PreferDualStack
      ports:
        http:
          port: 80
  ingress:
    excalidraw:
      className: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: *app
        gethomepage.dev/icon: excalidraw.svg
        gethomepage.dev/group: apps
      hosts:
        - host: draw.dex136.xyz
          paths:
            - path: /
              service:
                identifier: *app
                port: http