#!/bin/sh

overwrite=false

while getopts "o" arg; do
  case $arg in
    o) overwrite=true
  esac
done

terraform -chdir="./100-cluster-build" output -raw talos_config > 000-configs/generated_configs/TALOS_CONFIG
terraform -chdir="./100-cluster-build" output -raw kube_config > 000-configs/generated_configs/KUBE_CONFIG

if $overwrite; then
    cp 000-configs/generated_configs/TALOS_CONFIG ~/.talos/config
    cp 000-configs/generated_configs/KUBE_CONFIG ~/.kube/config
fi
