#!/bin/sh

apply=false
upgrade=false
init=false
cluster=false
external=false
while getopts "auice" arg; do
  case $arg in
    a) apply=true;;
    u) upgrade=true;;
    i) init=true;;
    c) cluster=true;;
    e) external=true;;
  esac
done

if $external; then
    if $upgrade; then
        terraform -chdir="./310-external-cluster-dependencies" init -upgrade
    elif $init; then
        terraform -chdir="./310-external-cluster-dependencies"
    fi
    if $apply; then
        terraform -chdir="./310-external-cluster-dependencies" apply -var-file=../000-configs/generated_configs/external.tfvars -auto-approve
    else
        terraform -chdir="./310-external-cluster-dependencies" plan -var-file=../000-configs/generated_configs/external.tfvars -no-color > 000-configs/generated_configs/310.tfplan
        cat 000-configs/generated_configs/310.tfplan
    fi
fi
if $cluster; then
    if $upgrade; then
        terraform -chdir="./100-cluster-build" init -upgrade
    elif $init; then
        terraform -chdir="./100-cluster-build" init
    fi
    if $apply; then
        terraform -chdir="./100-cluster-build" apply -var-file=../000-configs/generated_configs/cluster-build.tfvars -auto-approve
    else
        terraform -chdir="./100-cluster-build" plan -var-file=../000-configs/generated_configs/cluster-build.tfvars -no-color > 000-configs/generated_configs/100.tfplan
        cat 000-configs/generated_configs/100.tfplan
    fi
fi
