---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-secret
    template:
      engineVersion: v2
      data:
        PROWLARR__AUTH__APIKEY: {{"'{{ .PROWLARR_API_KEY }}'"}}
  dataFrom:
    - extract:
        key: prowlarr
