apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: external-secrets-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./minio-secret.sops.yaml
