---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          inhibit_rules:
          - equal: ["alertname", "namespace"]
            source_matchers:
              - severity = "critical"
            target_matchers:
              - severity = "warning"
          receivers:
          - name: discord_webhook
            discord_configs:
            - webhook_url: {{"{{ .DISCORD_ALERTMANGER_WEBHOOK }}"}}
          - name: "null"
          route:
            group_by:
            - alertname
            - job
            group_interval: 5m
            group_wait: 20s
            receiver: discord_webhook
            repeat_interval: 6h
            routes:
            - matchers:
              - alertname =~ "Watchdog"
              receiver: "null"
            - matchers:
              - alertname =~ "InfoInhibitor"
              receiver: "null"
            - continue: true
              receiver: discord_webhook
          templates:
          - /etc/alertmanager/config/*.tmpl
  dataFrom:
    - extract:
        key: discord
